import fs from 'fs';
import path from 'path';
import ConsoleLogger from '../../utils/logging/ConsoleLogger.js';
import { commonLog } from '../../utils/logging/Logger.js';
import { getCLIOptions } from '../CLIOptions.js';
import CommandLineParser from '../CommandLineParser.js';

export type InventorySelectResult = false | {
  hasError: boolean;
};

type ContentMediaType = 'image' | 'video' | 'audio' | 'attachment';

type InventoryTag = {
  id?: string | null;
  value?: string | null;
};

type InventoryMedia = {
  source?: string | null;
  type?: string | null;
  hasDownloadURL?: boolean;
};

type InventoryPostRecord = {
  type?: string;
  id?: string | null;
  url?: string | null;
  title?: string | null;
  publishedAt?: string | null;
  tags?: InventoryTag[];
  media?: InventoryMedia[];
};

const CONTENT_MEDIA_TYPES: ContentMediaType[] = [ 'image', 'video', 'audio', 'attachment' ];
const DEFAULT_INVENTORY_FILENAME = 'inventory.jsonl';
const DEFAULT_TARGETS_FILENAME = 'targets.txt';

export async function selectInventoryTargets(options: {
  onOptionError: (error: unknown) => Promise<void>;
}): Promise<InventorySelectResult> {
  try {
    if (!CommandLineParser.inventorySelect()) {
      return false;
    }
  }
  catch (error) {
    await options.onOptionError(error);
    return { hasError: true };
  }

  let cliOptions;
  try {
    cliOptions = getCLIOptions(true);
  }
  catch (error) {
    await options.onOptionError(error);
    return { hasError: true };
  }

  const consoleLogger = new ConsoleLogger(cliOptions.consoleLogger);
  const outDir = path.resolve(cliOptions.outDir || process.cwd());

  let inventoryInValue: string | undefined;
  let targetOutValue: string | undefined;
  let mediaTypes: ContentMediaType[];
  let tags: string[];
  let limit: number | undefined;
  try {
    inventoryInValue = CommandLineParser.inventoryIn();
    targetOutValue = CommandLineParser.targetOut();
    mediaTypes = parseMediaTypes(CommandLineParser.selectMedia());
    tags = parseList(CommandLineParser.selectTag()).map(normalizeMatchValue);
    limit = parseLimit(CommandLineParser.selectLimit());
  }
  catch (error) {
    await options.onOptionError(error);
    return { hasError: true };
  }

  const inventoryIn = path.resolve(inventoryInValue || path.join(outDir, '.patreon-dl', DEFAULT_INVENTORY_FILENAME));
  const targetOut = path.resolve(targetOutValue || path.join(outDir, '.patreon-dl', DEFAULT_TARGETS_FILENAME));

  try {
    const posts = readInventoryPosts(inventoryIn);
    const selected = selectPosts(posts, { mediaTypes, tags, limit });
    writeTargetsFile(targetOut, {
      inventoryIn,
      mediaTypes,
      tags,
      posts: selected
    });

    commonLog(consoleLogger, 'info', null, `Inventory posts read: ${posts.length}`);
    commonLog(consoleLogger, 'info', null, `Targets selected: ${selected.length}`);
    commonLog(consoleLogger, 'info', null, `Targets written to "${targetOut}"`);
  }
  catch (error) {
    commonLog(consoleLogger, 'error', null, 'Inventory selection error:', error);
    return { hasError: true };
  }

  return { hasError: false };
}

function readInventoryPosts(file: string) {
  const content = fs.readFileSync(file, 'utf-8');
  const posts: InventoryPostRecord[] = [];
  const lines = content.replace(/\r\n/g, '\n').split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) {
      continue;
    }
    let record: InventoryPostRecord;
    try {
      record = JSON.parse(line);
    }
    catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw Error(`Failed to parse inventory JSONL line ${i + 1}: ${message}`);
    }
    if (record.type === 'post') {
      posts.push(record);
    }
  }
  return posts;
}

function selectPosts(
  posts: InventoryPostRecord[],
  filters: { mediaTypes: ContentMediaType[]; tags: string[]; limit?: number; }
) {
  const selected: InventoryPostRecord[] = [];
  const seenURLs = new Set<string>();
  for (const post of posts) {
    if (!post.url || seenURLs.has(post.url)) {
      continue;
    }
    if (!matchesMediaTypes(post, filters.mediaTypes)) {
      continue;
    }
    if (!matchesTags(post, filters.tags)) {
      continue;
    }
    selected.push(post);
    seenURLs.add(post.url);
    if (filters.limit && selected.length >= filters.limit) {
      break;
    }
  }
  return selected;
}

function writeTargetsFile(file: string, args: {
  inventoryIn: string;
  mediaTypes: ContentMediaType[];
  tags: string[];
  posts: InventoryPostRecord[];
}) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const lines = [
    '# Generated by patreon-dl --inventory-select',
    `# Source inventory: ${args.inventoryIn}`,
    `# Selected posts: ${args.posts.length}`,
    `# Media filter: ${args.mediaTypes.length > 0 ? args.mediaTypes.join(',') : 'any'}`,
    `# Tag filter: ${args.tags.length > 0 ? args.tags.join(',') : 'any'}`
  ];
  const includeLines = getTargetIncludeLines(args.mediaTypes);
  for (const post of args.posts) {
    lines.push('');
    lines.push(`# ${sanitizeComment([ post.id, post.publishedAt ].filter((v) => !!v).join(' | '))}`);
    if (post.title) {
      lines.push(`# title: ${sanitizeComment(post.title)}`);
    }
    if (post.tags && post.tags.length > 0) {
      lines.push(`# tags: ${sanitizeComment(post.tags.map((tag) => tag.value || tag.id).filter((v) => !!v).join(', '))}`);
    }
    lines.push(post.url as string);
    lines.push(...includeLines);
  }
  fs.writeFileSync(file, `${lines.join('\n')}\n`, 'utf-8');
}

function getTargetIncludeLines(mediaTypes: ContentMediaType[]) {
  if (mediaTypes.length === 0) {
    return [];
  }
  const mediaList = mediaTypes.join(',');
  return [
    `include.posts.with.media.type = ${mediaList}`,
    `include.content.media = ${mediaList}`,
    'include.preview.media = 0'
  ];
}

function matchesMediaTypes(post: InventoryPostRecord, mediaTypes: ContentMediaType[]) {
  if (mediaTypes.length === 0) {
    return true;
  }
  const selectedTypes = new Set(mediaTypes);
  return (post.media || []).some((media) => {
    const type = getContentMediaType(media);
    return !!type && selectedTypes.has(type) && media.hasDownloadURL !== false;
  });
}

function getContentMediaType(media: InventoryMedia): ContentMediaType | null {
  switch (media.source) {
    case 'audio':
      return 'audio';
    case 'video':
      return 'video';
    case 'images':
      return 'image';
    case 'attachments':
    case 'linkedAttachments':
      return 'attachment';
    case 'embed':
      return media.type === 'videoEmbed' ? 'video' : null;
    default:
      return null;
  }
}

function matchesTags(post: InventoryPostRecord, tags: string[]) {
  if (tags.length === 0) {
    return true;
  }
  const postTags = (post.tags || []).flatMap((tag) => [ tag.id, tag.value ])
    .filter((value): value is string => !!value)
    .map(normalizeMatchValue);
  return tags.some((tag) => postTags.includes(tag));
}

function parseMediaTypes(value?: string) {
  const parsed = parseList(value).map((entry) => entry.toLowerCase());
  for (const entry of parsed) {
    if (!(CONTENT_MEDIA_TYPES as string[]).includes(entry)) {
      throw Error(`'--select-media' has invalid value '${entry}'. Expected one of: ${CONTENT_MEDIA_TYPES.join(', ')}`);
    }
  }
  return parsed as ContentMediaType[];
}

function parseLimit(value?: number) {
  if (value === undefined) {
    return undefined;
  }
  if (!Number.isInteger(value) || value <= 0) {
    throw Error("'--select-limit' must be a positive integer");
  }
  return value;
}

function parseList(value?: string) {
  if (!value) {
    return [];
  }
  return value.split(',').map((entry) => entry.trim()).filter((entry) => !!entry);
}

function normalizeMatchValue(value: string) {
  return value.trim().toLowerCase();
}

function sanitizeComment(value: string) {
  return value.replace(/\s+/g, ' ').trim();
}
